version: '3.8'

networks:
  abilitylink:
    driver: bridge

services:
  events:
    container_name: events
    build: ./events
    volumes:
      - ./events/:/usr/src/app
    networks:
      - abilitylink
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run watch"
  gateway:
    container_name: apigateway
    build: ./dynamischeGateway
    volumes:
      - ./dynamischeGateway/:/usr/src/app
    networks:
      - abilitylink
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"