version: '3.8'

networks:
  abilitylink:
    name: abilitylink
    driver: bridge

services:
  gateway:
    container_name: gateway
    image: node:20.10.0
    volumes:
      - ./gateway/:/usr/src/app
    networks:
      - abilitylink
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  events:
    container_name: events
    image: node:20.10.0
    volumes:
      - ./events:/usr/src/app
    networks:
      - abilitylink
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run watch"

  groups:
    container_name: groups
    image: node:20.10.0
    volumes:
      - ./groups/:/usr/src/app
    networks:
      - abilitylink
    ports:
      - "3012:3012"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run watch"

  login:
    container_name: login
    image: node:20.10.0
    volumes:
      - ./login:/usr/src/app
    networks:
      - abilitylink
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run watch"

  handicaps:
    container_name: handicaps
    image: node:20.10.0
    volumes:
      - ./handicaps:/usr/src/app
    networks:
      - abilitylink
    ports:
      - "3015:3015"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run watch"
