name: deploy-backend
run-name: ${{ github.actor }} is deploying...
on: [push]
jobs:
    deploy-to-server:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                node-version: '14'
            - name: Setup Gateway
              working-directory: ./gateway
              run: npm install