name: run-test-suites

on:
  push:

jobs:
  run-test-suites:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Setup gateway microservice
        working-directory: ./gateway
        run: |
          npm install
          npm test

      - name: Install ESLint
        working-directory: ./gateway
        run: npm install eslint --save-dev

      - name: Run ESLint
        working-directory: ./gateway
        run: npx eslint .
        continue-on-error: true

      - name: Install cloc and plato
        run: |
          npm install cloc plato --save-dev

      # - name: Count Lines of Code
      #   working-directory: ./gateway
      #   run: npx cloc .


      - name: Run Plato (Cyclomatic Complexity)
        working-directory: ./
        run: |
          npx find . -type f -name '*.js' -not -path './node_modules/*' -print0 | xargs -0 npx plato -r -d report -x 'node_modules'
    

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Switch to gh-pages branch
        run: |
          pwd
          ls
          git branch
          pwd
          ls
          git fetch
          pwd
          ls
          git pull
          pwd
          ls
          git stash
          pwd
          ls
          git checkout -f gh-pagina 
          pwd
          ls

      - name: Print current working directory
        run: |
          pwd

      - name: Delete existing temp directory
        run: rm -rf temp
        continue-on-error: true

      - name: Create a temporary directory
        run: mkdir temp

      - name: Copy all files from report to temp
        run: cp -r ./report/* temp

      - name: Copy all files from temp to the root
        run: cp -r temp/* .

      - name: Add all files to the commit
        run: git add .

      - name: Commit and push changes
        run: |
          git commit -m "Update GitHub Pages with Plato report"
          git push origin gh-pagina 