name: run-test-suites

on:
  push:
    branches:

jobs:
  run-test-suites:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Setup gateway microservice
        working-directory: ./gateway
        run: |
          npm install
          npm test

      - name: Install ESLint
        working-directory: ./gateway
        run: npm install eslint --save-dev

      - name: Run ESLint
        working-directory: ./gateway
        run: npx eslint .
        continue-on-error: true

      - name: Install cloc and plato
        run: |
          npm install cloc plato --save-dev

      - name: Count Lines of Code
        working-directory: ./gateway
        run: npx cloc .

      - name: Run Plato (Cyclomatic Complexity)
        working-directory: ./gateway
        run: npx plato -r -d report src/ --exclude **/*.test.js

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Deploy to GitHub Pages
        run: |
          # Create a temporary directory
          mkdir temp
          cp -r ./gateway/report/* temp

          # Switch to the gh-pages branch
          git checkout gh-pages

          # Fetch and pull
          git pull origin gh-pages

          # Copy all files from temp to the root
          cp -r temp/* .

          # Add all files to the commit
          git add .

          # Commit and push changes
          git commit -m "Update GitHub Pages with Plato report"
          git push origin gh-pages